apiVersion: v1
kind: Pod
metadata:
  name: db-app
  namespace: default
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "db-app"
    vault.hashicorp.com/agent-inject-secret-db-creds.txt: "secret/data/db-creds"
    vault.hashicorp.com/agent-inject-template-db-creds.txt: |
      {{- with secret "secret/data/db-creds" -}}
      username="{{ .Data.data.username }}"
      password="{{ .Data.data.password }}"
      {{- end }}
spec:
  serviceAccountName: db-app
  containers:
    - name: app
      image: postgres
      envFrom:
        - secretRef:
            name: dummy-secret # not used, just placeholder if needed
      command: [ "sleep", "3600" ]
